spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    username: postgres
    password: 12345678
    url: jdbc:postgresql://localhost:5433/employeeDB

server:
  port: 6162
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
